import { ArrowLeft, ArrowRight, CheckCircle2, FileCheck2, FileUp, LockKeyhole, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function AccessRequest() {
  const [, setLocation] = useLocation();
  const fileRef = useRef<HTMLInputElement>(null);
  const submit = trpc.access.submit.useMutation({ onSuccess: () => setSubmitted(true), onError: (error: any) => toast.error(error.message || "신청을 제출하지 못했습니다.") });
  const [submitted, setSubmitted] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [form, setForm] = useState({ applicantName: "", email: "", password: "", organization: "", organizationType: "local_government", jobTitle: "" });
  const update = (key: keyof typeof form, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  const submitForm = async (event: React.FormEvent) => { event.preventDefault(); if (!file) { toast.error("재직증명서 또는 기관 증빙파일을 첨부해주세요."); return; } if (form.password.length < 8) { toast.error("비밀번호는 8자 이상이어야 합니다."); return; } const data = await file.arrayBuffer(); const bytes = new Uint8Array(data); let binary = ""; bytes.forEach((byte) => binary += String.fromCharCode(byte)); const documentData = `data:${file.type};base64,${btoa(binary)}`; submit.mutate({ ...form, organizationType: form.organizationType as "local_government" | "travel_company" | "other", documentName: file.name, documentType: file.type || "application/octet-stream", documentData }); };
  if (submitted) return <div className="apply-shell"><div className="apply-success"><div className="success-mark"><CheckCircle2 size={36} /></div><span className="blue-kicker">APPLICATION RECEIVED</span><h1>접근 신청이 접수되었습니다.</h1><p>운영자가 제출하신 기관 정보와 증빙파일을 확인한 뒤<br />승인 결과를 이메일로 안내드릴게요.</p><div className="success-note"><LockKeyhole size={17} /><span>승인 전까지는 분석 데이터에 접근할 수 없습니다.</span></div><Link href="/" className="hero-primary">처음으로 돌아가기 <ArrowRight size={17} /></Link></div></div>;
  return <div className="apply-shell"><div className="apply-card"><Link href="/" className="back-link"><ArrowLeft size={15} />서비스 소개로 돌아가기</Link><div className="apply-heading"><div className="apply-mini-logo">●</div><span className="blue-kicker">FOR ORGANIZATIONS</span><h1>Trip Ping Insight<br /><em>접근 신청</em></h1><p>기업·지자체 담당자임을 확인하기 위한 정보입니다.</p></div><form onSubmit={submitForm}><div className="form-grid"><label>이름<input value={form.applicantName} onChange={(e) => update("applicantName", e.target.value)} placeholder="홍길동" required /></label><label>업무용 이메일<input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} placeholder="name@organization.go.kr" required /></label><label>로그인 비밀번호<input type="password" value={form.password} onChange={(e) => update("password", e.target.value)} placeholder="8자 이상" minLength={8} required /></label><label className="wide">기관명<input value={form.organization} onChange={(e) => update("organization", e.target.value)} placeholder="소속 기관 또는 기업명" required /></label><label>기관 유형<select value={form.organizationType} onChange={(e) => update("organizationType", e.target.value)}><option value="local_government">지자체·공공기관</option><option value="travel_company">여행사·관광기업</option><option value="other">기타 관광 관련 기관</option></select></label><label>직무<input value={form.jobTitle} onChange={(e) => update("jobTitle", e.target.value)} placeholder="관광기획 / 상품개발" required /></label></div><div className="upload-label">재직·소속 증빙 <span>필수</span></div><button type="button" className={file ? "upload-box has-file" : "upload-box"} onClick={() => fileRef.current?.click()}><input ref={fileRef} type="file" accept=".pdf,.png,.jpg,.jpeg" hidden onChange={(e) => setFile(e.target.files?.[0] ?? null)} />{file ? <><FileCheck2 size={24} /><b>{file.name}</b><span>{(file.size / 1024 / 1024).toFixed(2)}MB · 업로드 준비 완료</span></> : <><UploadCloud size={24} /><b>재직증명서 또는 기관 증빙파일 업로드</b><span>PDF, JPG, PNG · 최대 8MB</span></>}</button><div className="privacy-note"><LockKeyhole size={14} />제출한 증빙파일은 운영자 확인 목적으로만 사용되며 안전하게 보관됩니다.</div><button className="submit-application" type="submit" disabled={submit.isPending}>{submit.isPending ? "신청 제출 중..." : "접근 신청 제출"}<ArrowRight size={17} /></button></form><div className="apply-login-note">이미 승인된 계정이 있나요? <button onClick={() => setLocation("/")}>서비스 소개에서 로그인</button></div></div></div>;
}
