import { ArrowRight, BarChart3, Check, ChevronRight, Clock3, FileCheck2, Gauge, LogIn, LogOut, Map, Menu, Network, Route, Sparkles, TrendingUp, Users, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { user, logout } = useAuth();
  const accessStatus = trpc.access.status.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const isApproved = user?.role === "admin" || accessStatus.data?.status === "approved";
  const handleLogout = async () => { await logout(); toast.success("로그아웃되었습니다."); };
  return (
    <div className="landing-shell">
      <header className="landing-nav"><Link href="/" className="landing-brand"><span className="landing-logo"><i /><i /><i /></span><span><b>trip ping</b><small>INSIGHT PORTAL</small></span></Link><nav className={menuOpen ? "landing-links open" : "landing-links"}><a href="#why">왜 Trip Ping인가</a><a href="#how">이용 방법</a><a href="#features">주요 기능</a>{user ? <>{isApproved ? <Link href="/dashboard" className="nav-dashboard"><Gauge size={16} />대시보드 보기</Link> : <Link href="/pending" className="nav-login"><Clock3 size={16} />승인 상태</Link>}<button className="nav-login" onClick={handleLogout}><LogOut size={16} />로그아웃</button></> : <button className="nav-login" onClick={() => { window.location.href = "/login"; }}><LogIn size={16} />로그인</button>}<Link href="/apply" className="nav-apply">접근 신청 <ArrowRight size={15} /></Link></nav><button className="landing-menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></header>
      <main>
        <section className="landing-hero"><div className="hero-copy"><div className="hero-kicker"><span className="live-dot" />TOURISM ROUTE INTELLIGENCE</div><h1>변화하는 여행 트렌드에<br /><em>더 빠르게</em> 도착하는 방법</h1><p>Trip Ping은 실제 여행객의 이동 경로와 방문 순서를 분석해<br />지자체와 여행사가 바로 활용할 수 있는 여행 루트를 제안합니다.</p><div className="hero-actions"><Link href="/apply" className="hero-primary">기업·기관 접근 신청 <ArrowRight size={17} /></Link><button className="hero-secondary" onClick={() => { window.location.href = "/login"; }}>승인 계정 로그인 <LogIn size={16} /></button></div><div className="hero-proof"><div className="proof-avatars"><i>K</i><i>관</i><i>여</i><i>+</i></div><span><b>검증된 기관 계정</b><br />운영자 승인 후 안전하게 이용</span></div></div><div className="hero-visual"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="route-preview-card"><div className="route-card-top"><span><Map size={15} />LIVE ROUTE PULSE</span><i>● 분석 중</i></div><div className="route-city"><b>제주 동부 해안 루트</b><span>최근 30일 급상승</span></div><div className="route-path"><div className="route-point first"><i /><span>성산일출봉</span></div><div className="route-line blue-line" /><div className="route-point"><i /><span>섭지코지</span></div><div className="route-line green-line" /><div className="route-point last"><i /><span>우도</span></div></div><div className="route-card-bottom"><b>+24.8%</b><span>실제 이동량 증가</span><button onClick={() => toast.info("상세 루트 분석은 승인 계정에서 확인할 수 있습니다.")}><ChevronRight size={16} /></button></div></div><div className="floating-insight insight-top"><TrendingUp size={17} /><div><b>급상승 트렌드</b><span>제주 동부 +24.8%</span></div></div><div className="floating-insight insight-bottom"><Sparkles size={17} /><div><b>새 루트 기회</b><span>상품 초안으로 연결</span></div></div></div></section>
        <section className="trust-strip"><span>실제 움직임에서 발견하는 인사이트</span><div><span><Route size={16} />여행객 루트 데이터</span><span><Network size={16} />관광지 네트워크</span><span><FileCheck2 size={16} />기관용 보고서</span></div></section>
        <section className="landing-section why-section" id="why"><div className="section-intro"><span className="blue-kicker">WHY TRIP PING</span><h2>관광 수요가 바뀐 뒤가 아니라,<br /><em>바뀌는 순간</em>을 읽습니다.</h2><p>기존 관광상품은 조사부터 기획, 검증까지 많은 시간이 걸립니다. Trip Ping은 여행객이 실제로 남긴 동선을 매일 쌓아 변화하는 수요를 빠르게 포착합니다.</p></div><div className="why-grid"><div className="why-card"><div className="why-icon blue"><Clock3 /></div><b>느린 조사 대신 실시간 흐름</b><p>주간·월간 방문 변화와 급상승 루트를 한눈에 확인합니다.</p></div><div className="why-card"><div className="why-icon mint"><Network /></div><b>관광지 나열 대신 이동 맥락</b><p>어떤 장소를 어떤 순서로 함께 방문하는지 연결해서 봅니다.</p></div><div className="why-card"><div className="why-icon orange"><Sparkles /></div><b>분석에서 바로 상품 초안</b><p>발견한 루트를 일정과 방문 순서가 있는 상품으로 확장합니다.</p></div></div></section>
        <section className="landing-section how-section" id="how"><div className="section-intro centered"><span className="blue-kicker">HOW IT WORKS</span><h2>신청하고, 승인받고,<br /><em>빠르게 루트를 만드세요.</em></h2><p>기업·기관의 관광 데이터 활용을 위해 확인 가능한 계정만 운영합니다.</p></div><div className="how-steps"><div><span>01</span><FileCheck2 /><b>기관 정보와<br />재직 증빙 제출</b><p>소속·직무·증빙파일을 한 번에 제출합니다.</p></div><div><span>02</span><Users /><b>운영자 검토 및<br />접근 승인</b><p>확인된 기관 계정만 분석 화면에 접근합니다.</p></div><div><span>03</span><Map /><b>트렌드에서<br />루트 상품으로</b><p>인기 조합과 급상승 동선을 바로 활용합니다.</p></div></div></section>
        <section className="landing-cta" id="features"><div><span className="blue-kicker">READY TO MOVE WITH THE TREND?</span><h2>다음 여행상품의 시작을<br /><em>실제 동선</em>에서 찾아보세요.</h2></div><Link href="/apply" className="hero-primary">접근 신청하기 <ArrowRight size={17} /></Link></section>
      </main><footer className="landing-footer"><Link href="/" className="landing-brand"><span className="landing-logo"><i /><i /><i /></span><span><b>trip ping</b><small>INSIGHT PORTAL</small></span></Link><span>© 2026 Trip Ping Insight Portal · 기관용 관광 데이터 플랫폼</span><span>개인정보처리방침 · 이용약관</span></footer>
    </div>
  );
}
